### ISSUE TITLE
Product Dashboard

### ISSUE THREAD

**Issue by meyerdan** [cawemo/tasks#26]
We should create a product dashboard which shows key metics for our product's success.

Proposal:

* Daily Active Users over time (last Month)
* Daily Signups over time (last Month) + Total Signups
* Daily Service Availability in Percent over time (last Month)

Dashboard will be shown on a TV in product office. Also, it should be available for everyone in Camunda. It should not be publicly visible.

**Comment by AndreaGiardini** [comment]
@meyerdan  Wrong repo :) New issue here camunda/cawemo#1137
