### ISSUE TITLE
Add updated field to diagrams, but keep created field after removing the diagram revisions

### ISSUE THREAD

**Issue by cmoisuc** [cawemo/tasks#31]
As discussed with @cmur2, after we remove the diagram revisions, we will not have the date when the diagram was created anymore, because right now we are updating the "created" field with the time when the diagram was updated.

I suggest that we add a new field named: "updated" and update that field at every diagram update and leave the date of creation be in the field "created".

**Comment by cmoisuc** [comment]
Depends on #1160. Must be done after the diagram revisions are deleted.

**Comment by AndreaGiardini** [comment]
@cmoisuc Wrong repo!
